// Generated by Wrangler by running `wrangler types`

interface Env {
	DB_USER: string;
	DB_HOST: string;
	DB_NAME: string;
	DB_PASSWORD: string;
	DB_PORT: string;
	DB_SSL_REJECT_UNAUTHORIZED: string;
	DATABASE_URL: string;
	SECRET_KEY: string;
}
